"""Platform kernel — tenants, users, operators, client access, sessions.

Revision ID: 0002_platform_kernel
Revises: 0001_baseline
Created: 2026-08-05

🔒 **D0 — the dependency root.** DB §21.1: *"`tenants` is the FK target of every
tenant-scoped table. Nothing can be created before it exists."* Every later
migration in the project depends on this one.

Hand-written rather than autogenerated. Alembic's `--autogenerate` requires a
live database and infers only what SQLAlchemy models express — it cannot see RLS
policies, `FORCE ROW LEVEL SECURITY`, or the DDR-15 grant revocations, all of
which are load-bearing here. The models and this migration are checked against
each other by `tests/test_kernel_schema.py` instead.

🔒 What this migration establishes beyond tables:

1. **RLS on every tenant-scoped table** (DB §17.1 Pattern A). Enabled *and*
   forced — `FORCE` is what makes the policy apply to the table's owner too.
2. **`tenants` and `operators` deliberately have no RLS** (Pattern D). They are
   platform tables, unreachable from a client-facing path, and `tenants` cannot
   filter on `app.tenant_id` because it *defines* it.
3. **Session-variable helper** — `current_tenant_id()`, so every policy reads
   the setting identically rather than repeating a cast that could drift.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_platform_kernel"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ─── Enum types (DDR-02: ENUM for closed sets) ───────────────────────────
#
# 🔒 Named in singular snake_case per DB §1 naming rules, and created
# explicitly rather than inline so `downgrade()` can drop them. A type created
# implicitly by a column is not dropped when the column goes, which makes a
# rollback-then-reapply fail with "type already exists".

_ENUMS: dict[str, tuple[str, ...]] = {
    "tenant_status": ("trial", "active", "suspended", "closed"),
    "user_role": ("owner", "practitioner"),
    "user_status": ("invited", "active", "disabled"),
    "access_status": ("active", "revoked"),
    "link_purpose": ("portal", "assessment", "plan_view"),
    "transport_type": ("whatsapp", "sms", "email"),
    "auth_realm": ("practitioner", "client", "operator"),
}

# 🔒 Tables carrying `tenant_id`, and therefore requiring Pattern A RLS.
# `tenants` and `operators` are absent by design — see the module docstring.
_TENANT_SCOPED: tuple[str, ...] = (
    "users",
    "client_access_grants",
    "magic_links",
)


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created enum type without re-emitting its DDL.

    ⚠️ A real defect caught by rendering the migration with ``--sql``, not by
    reading it. ``sa.Enum(name=..., create_type=False)`` still emits
    ``CREATE TYPE <name> AS ENUM ()`` — an *empty* type — when the column is
    compiled inside ``create_table``, because ``create_type`` governs the
    checkfirst behaviour rather than suppressing inline emission. The result is
    a migration that creates each type twice, the second time with no values,
    and fails on a real server with "type already exists".

    ``postgresql.ENUM(name=..., create_type=False)`` is the form that genuinely
    emits nothing: the values are declared once, explicitly, in ``upgrade()``.
    """
    return postgresql.ENUM(name=name, create_type=False)


def upgrade() -> None:
    for name, values in _ENUMS.items():
        sa.Enum(*values, name=name).create(op.get_bind(), checkfirst=False)

    # 🔒 Read the tenant setting in one place. `true` as the second argument
    # means "missing setting returns NULL rather than raising" — without it, an
    # unscoped connection would error instead of simply matching no rows, and a
    # policy that raises is a policy that gets worked around.
    op.execute(
        """
        CREATE FUNCTION current_tenant_id() RETURNS uuid
        LANGUAGE sql STABLE
        AS $$ SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid $$;
        """
    )

    # ─── tenants (DB §4.1) ───────────────────────────────────────────────
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("region_code", sa.Text(), server_default="IN", nullable=False),
        sa.Column("timezone", sa.Text(), server_default="Asia/Kolkata", nullable=False),
        sa.Column("currency_code", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column(
            "status",
            _enum("tenant_status"),
            server_default="trial",
            nullable=False,
        ),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_retention_days", sa.Integer(), server_default="2555", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_tenants"),
        sa.UniqueConstraint("slug", name="uq_tenants__slug"),
    )
    op.create_index("ix_tenants__status", "tenants", ["status"])

    # ─── users (DB §4.2) ─────────────────────────────────────────────────
    # 🔒 No password, hash or salt column. Credentials live in GoTrue
    # (NFR-029) — we cannot leak what we do not store.
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("auth_subject_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("mobile", sa.Text(), nullable=True),
        sa.Column("role", _enum("user_role"), nullable=False),
        sa.Column(
            "status",
            _enum("user_status"),
            server_default="invited",
            nullable=False,
        ),
        sa.Column("is_two_factor_enabled", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="fk_users__tenant"),
        sa.UniqueConstraint("auth_subject_id", name="uq_users__auth_subject"),
        sa.CheckConstraint(
            r"mobile IS NULL OR mobile ~ '^\+[1-9][0-9]{1,14}$'",
            name="ck_users__mobile_e164",
        ),
    )
    op.create_index("ix_users__tenant_status", "users", ["tenant_id", "status"])
    # 🔒 Partial unique: an archived user's email may be reused (EC-M1-04),
    # two *active* users may not share one within a tenant.
    op.create_index(
        "uq_users__tenant_email",
        "users",
        ["tenant_id", "email"],
        unique=True,
        postgresql_where=sa.text("archived_at IS NULL"),
    )

    # ─── operators (DB §4.3) ─────────────────────────────────────────────
    # 🔒 No `tenant_id`, and no RLS. An operator belongs to no tenant — that is
    # what makes them cross-tenant, and why every clinical read they perform is
    # audited (FR-M0-032). A separate table rather than a role on `users` makes
    # cross-realm authentication structurally impossible (AC-M11-005).
    op.create_table(
        "operators",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("auth_subject_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        # 🔒 Defaults to true — FR-M0-009 / AC-M11-004 require 2FA for operators.
        sa.Column("is_two_factor_enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("status", _enum("user_status"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_operators"),
        sa.UniqueConstraint("auth_subject_id", name="uq_operators__auth_subject"),
        sa.UniqueConstraint("email", name="uq_operators__email"),
    )

    # ─── client_access_grants (DB §4.4) ──────────────────────────────────
    # 🔒 The client realm's identity anchor. Clients are not `users`
    # (FR-M0-005). No FK to `clients` — that table lands in S2, and adding the
    # constraint then is a one-line migration.
    op.create_table(
        "client_access_grants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            _enum("access_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_client_access_grants"),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="fk_client_access_grants__tenant"
        ),
        sa.UniqueConstraint("client_id", name="uq_client_access_grants__client"),
    )
    op.create_index("ix_client_access_grants__tenant", "client_access_grants", ["tenant_id"])

    # ─── magic_links (DB §4.5) ───────────────────────────────────────────
    # 🔒 DDR-04 — the hash is stored, never the token. A database read must not
    # yield working credentials. Single-use is enforced by the unique constraint
    # plus a conditional update, not an application check, which is what closes
    # the double-redemption race.
    op.create_table(
        "magic_links",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("purpose", _enum("link_purpose"), nullable=False),
        sa.Column("target_ref", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_via", _enum("transport_type"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_magic_links"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="fk_magic_links__tenant"),
        sa.UniqueConstraint("token_hash", name="uq_magic_links__token_hash"),
    )
    op.create_index("ix_magic_links__client_expires", "magic_links", ["client_id", "expires_at"])

    # ─── sessions (DB §4.6) ──────────────────────────────────────────────
    # 🔒 DDR-05 — rotating refresh with reuse detection. `previous_token_hash`
    # is what makes a replayed token detectable; presenting one revokes the
    # whole family rather than issuing to the attacker.
    #
    # ⚠️ No RLS: sessions span realms and operator rows have no `tenant_id`, so
    # a Pattern A policy would silently hide every operator session. Access is
    # confined to `kernel.identity`, which never runs on a client-facing path.
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("realm", _enum("auth_realm"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column("previous_token_hash", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        sa.Column("user_agent_hash", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_sessions"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="fk_sessions__tenant"),
        sa.UniqueConstraint("refresh_token_hash", name="uq_sessions__refresh_token_hash"),
    )
    op.create_index("ix_sessions__subject_expires", "sessions", ["subject_id", "expires_at"])

    # ─── Row Level Security (DB §17.1 Pattern A) ─────────────────────────
    #
    # 🔒 ADR-06. This is the seatbelt: a forgotten `WHERE tenant_id` in
    # application code returns nothing rather than another tenant's data.
    #
    # 🔒 `FORCE ROW LEVEL SECURITY` is not redundant with `ENABLE`. Without
    # FORCE, the table *owner* bypasses every policy. Migrations run as
    # `app_migrator`, which owns these tables, so an unforced table would leave
    # policies inert for exactly the role most likely to be used in a fix-up
    # script. `app_user` is not the owner and would be filtered either way —
    # FORCE closes the gap for everyone else.
    for table in _TENANT_SCOPED:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}__tenant_isolation ON {table}
            USING (tenant_id = current_tenant_id())
            WITH CHECK (tenant_id = current_tenant_id());
            """
        )

    # 🔒 WITH CHECK, not only USING. USING filters what is *read*; WITH CHECK
    # constrains what is *written*. Without it a tenant could INSERT a row
    # carrying someone else's `tenant_id` — invisible to them afterwards, but
    # present in the other tenant's data.


def downgrade() -> None:
    """Drop everything this revision created, in dependency order.

    ⚠️ Destroys all tenant, user and session data. This exists so the chain is
    honestly reversible in development; it is not a production operation.
    """
    for table in ("sessions", "magic_links", "client_access_grants", "operators", "users"):
        op.drop_table(table)
    op.drop_table("tenants")

    op.execute("DROP FUNCTION IF EXISTS current_tenant_id()")

    for name in _ENUMS:
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=False)
